- name: Install mysql
  become: yes
  hosts: mongodb
  vars_prompt:
    - name: PASSWORD
      prompt: Enter_passwordCRoboCShop@1C
      private: false
  tasks:
  - name: Install mysql-server
    ansible.builtin.dnf:
      name: mysql-server
      state: present

  - name: Start service httpd, if not started
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: We need to change the default root password in order to start using the database service
    ansible.builtin.shell: mysql_secure_installation --set-root-pass {{PASSWORD}}
  