- name: Install rabbitmq-server
  become: yes
  hosts: rabbitmq
  tasks:
  - name: copy repo file
    ansible.builtin.copy:
      src: rabbitmq.repo
      dest: vim /etc/yum.repos.d/rabbitmq.repo

  - name: Install rabbitmq-server
    ansible.builtin.dnf:
      name: rabbitmq-server
      state: present
      
  - name: Start service httpd, if not started
    ansible.builtin.service:
      name: rabbitmq-server
      state: started
      enabled: yes

  # - name: add roboshop user
  #   ansible.builtin.command: rabbitmqctl add_user roboshop roboshop123

  - name: rabbitmq permissionsdd user to server and assign full access control on / vhost.The user doesn't have permission rules for other vhosts
    community.rabbitmq.rabbitmq_user:
      user: roboshop
      password: roboshop123
      permissions:
        - vhost: /
          configure_priv: .*
          read_priv: .*
          write_priv: .*
      state: present


    