- name: user microservice
  hosts: user
  become: yes
  tasks:
  - name: module disable node
    ansible.builtin.command: dnf module disable nodejs -y

  - name: module enable nodejs:20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present

  - name: create roboshop system user
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      system: true 
      home: /app


  - name: Create a directory if it does not exist
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Downloading user zip file
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
      dest: /tmp/user.zip

   # this module thinks file exist on ansible control server, needs to extract on to remote machine
  # remote_src: yes means files already exist in user server
  - name: Unarchive a user file
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: yes

  
  - name: insatll dependices
    community.general.npm:
      path: /app

  - name: copy user.service file
    ansible.builtin.copy:
      src: user.service
      dest: /etc/systemd/system/user.service
    
  - name: user system deamon reload
    ansible.builtin.systemd_service:
      daemon_reload:  true

  - name: Start service httpd, if not started
    ansible.builtin.service:
      name: user
      state: started
      enabled: yes
    
    # ansible-playbook -i inventory.ini user.yaml &>> /home/ec2-user/user.log & - this will run in backgroupnd
    # we can store our logs 